server:
  port: 8080



spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      
    
      routes:
        - id: CONTACTUS-SERVICE
          uri: lb://CONTACTUS-SERVICE
          predicates:
            - Path=/contact/** 
            
        - id: BLOGS-SERVICE
          uri: lb://BLOGS-SERVICE
          predicates:
            - Path=/blog/**
            
        - id: FEEDBACK-SERVICE
          uri: lb://FEEDBACK-SERVICE
          predicates:
            - Path=/feedback/**
            
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
            
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**
            
            
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true   
  instance:
    hostname: localhost     



management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true



